#              Murder Configuration File
#
#         You can edit all the settings of the
#       plugin here. Make sure to read everything
#      before editing, so you don't break anything

# Which item should be the murder weapon?
murder-weapon: IRON_SWORD

# How many second before a detective can shoot again?
# (Time before they are given another arrow)
detective-bow-recharge-time: 5

# How many seconds should a detective be punished for shooting an innocent?
detective-punishment-time: 10

# How many clues should a player find before becoming detective?
player-min-clues: 6

# How long should each round be in seconds?
game-time: 270

# What's the minimum amount of players needed before a game can start? (default = 4)
game-min-players: 4

# What's the maximum amount of players in a game? (default = 10)
game-max-players: 10

# Should the game start automatically when reaching minimum players? (default = false)
game-auto-start: false

# How many clues can be in an arena at the same time? (default = 5)
arena-clues-max: 5

# How many seconds must pass before another clue spawns? (default = 5)
arena-clues-spawn-time: 5