name: Murder
version: ${project.version}
main: net.phoenix1355.murder.Murder
api-version: 1.13
authors: [Phoenix1355]
description: A gamemode for Minecraft Spigot Servers inspired by Murder from Garrys Mod
website: https://bohlbro.dk/mc-murder

commands:
  murder:
    description: Murder commands
    usage: "\u00A76Correct usage: /m [join/leave]"
    aliases: [mm]

permissions:
  murder.admin.*:
    default: op
    children:
      murder.admin: true
      murder.admin.room.create: true
      murder.admin.room.delete: true
      murder.admin.room.edit: true
      murder.admin.room.edit.setspawn: true
      murder.admin.arena.create: true
      murder.admin.arena.delete: true
      murder.admin.arena.edit.clue.create: true
      murder.admin.arena.edit.clue.delete: true
      murder.admin.arena.edit.spawn.create: true
      murder.admin.arena.edit.spawn.delete: true

